# 100 Common English-Polish Word Pairs


word_pairs = [
    ("hello", "cześć"),
    ("goodbye", "do widzenia"),
    ("please", "proszę"),
    ("thank you", "dziękuję"),
    ("yes", "tak"),
    ("no", "nie"),
    ("excuse me", "przepraszam"),
    ("water", "woda"),
    ("bread", "chleb"),
    ("food", "jedzenie"),
    ("house", "dom"),
    ("car", "samochód"),
    ("school", "szkoła"),
    ("work", "praca"),
    ("money", "pieniądze"),
    ("time", "czas"),
    ("day", "dzień"),
    ("night", "noc"),
    ("morning", "rano"),
    ("evening", "wieczór"),
    ("today", "dzisiaj"),
    ("tomorrow", "jutro"),
    ("yesterday", "wczoraj"),
    ("week", "tydzień"),
    ("month", "miesiąc"),
    ("year", "rok"),
    ("friend", "przyjaciel"),
    ("family", "rodzina"),
    ("mother", "matka"),
    ("father", "ojciec"),
    ("sister", "siostra"),
    ("brother", "brat"),
    ("child", "dziecko"),
    ("person", "osoba"),
    ("name", "imię"),
    ("book", "książka"),
    ("phone", "telefon"),
    ("computer", "komputer"),
    ("table", "stół"),
    ("chair", "krzesło"),
    ("door", "drzwi"),
    ("window", "okno"),
    ("room", "pokój"),
    ("city", "miasto"),
    ("country", "kraj"),
    ("road", "droga"),
    ("street", "ulica"),
    ("shop", "sklep"),
    ("restaurant", "restauracja"),
    ("hotel", "hotel"),
    ("train", "pociąg"),
    ("bus", "autobus"),
    ("airplane", "samolot"),
    ("good", "dobry"),
    ("bad", "zły"),
    ("big", "duży"),
    ("small", "mały"),
    ("hot", "gorący"),
    ("cold", "zimny"),
    ("new", "nowy"),
    ("old", "stary"),
    ("beautiful", "piękny"),
    ("difficult", "trudny"),
    ("easy", "łatwy"),
    ("happy", "szczęśliwy"),
    ("sad", "smutny"),
    ("tired", "zmęczony"),
    ("hungry", "głodny"),
    ("to go", "iść"),
    ("to come", "przyjść"),
    ("to eat", "jeść"),
    ("to drink", "pić"),
    ("to sleep", "spać"),
    ("to speak", "mówić"),
    ("to listen", "słuchać"),
    ("to read", "czytać"),
    ("to write", "pisać"),
    ("to buy", "kupować"),
    ("to know", "wiedzieć"),
    ("to understand", "rozumieć"),
    ("to like", "lubić"),
    ("to love", "kochać"),
    ("to help", "pomagać"),
    ("to work", "pracować"),
    ("to live", "żyć"),
    ("to want", "chcieć"),
    ("to need", "potrzebować"),
    ("to have", "mieć"),
    ("to be", "być"),
    ("one", "jeden"),
    ("two", "dwa"),
    ("three", "trzy"),
    ("four", "cztery"),
    ("five", "pięć"),
    ("ten", "dziesięć"),
    ("hundred", "sto"),
    ("thousand", "tysiąc"),
    ("here", "tutaj"),
    ("there", "tam"),
    ("now", "teraz"),
    ("later", "później"),
    ("always", "zawsze"),
    ("never", "nigdy"),
    ("sea", "morze"),
    ("sky", "niebo"),
    ("sun", "słońce"),
    ("moon", "księżyc"),
    ("star", "gwiazda"),
    ("rain", "deszcz"),
    ("snow", "śnieg"),
    ("wind", "wiatr"),
    ("tree", "drzewo"),
    ("flower", "kwiat"),
    ("animal", "zwierzę"),
    ("dog", "pies"),
    ("cat", "kot"),
    ("bird", "ptak"),
    ("fish", "ryba"),
    ("fruit", "owoc"),
    ("vegetable", "warzywo"),
    ("meat", "mięso"),
    ("cheese", "ser"),
    ("milk", "mleko"),
    ("coffee", "kawa"),
    ("tea", "herbata"),
    ("juice", "sok"),
    ("beer", "piwo"),
    ("wine", "wino"),
    ("sugar", "cukier"),
    ("salt", "sól"),
    ("hour", "godzina"),
    ("minute", "minuta"),
    ("second", "sekunda"),
    ("clock", "zegar"),
    ("watch", "zegarek"),
    ("Monday", "poniedziałek"),
    ("Tuesday", "wtorek"),
    ("Wednesday", "środa"),
    ("Thursday", "czwartek"),
    ("Friday", "piątek"),
    ("Saturday", "sobota"),
    ("Sunday", "niedziela"),
    ("January", "styczeń"),
    ("February", "luty"),
    ("March", "marzec"),
    ("April", "kwiecień"),
    ("May", "maj"),
    ("June", "czerwiec"),
    ("July", "lipiec"),
    ("August", "sierpień"),
    ("September", "wrzesień"),
    ("October", "październik"),
    ("November", "listopad"),
    ("December", "grudzień"),
    ("spring", "wiosna"),
    ("summer", "lato"),
    ("autumn", "jesień"),
    ("winter", "zima"),
    ("husband", "mąż"),
    ("wife", "żona"),
    ("son", "syn"),
    ("daughter", "córka"),
    ("grandfather", "dziadek"),
    ("grandmother", "babcia"),
    ("uncle", "wujek"),
    ("aunt", "ciocia"),
    ("cousin", "kuzyn"),
    ("color", "kolor"),
    ("red", "czerwony"),
    ("blue", "niebieski"),
    ("green", "zielony"),
    ("yellow", "żółty"),
    ("black", "czarny"),
    ("white", "biały"),
    ("orange", "pomarańczowy"),
    ("purple", "fioletowy"),
    ("brown", "brązowy"),
    ("gray", "szary"),
    ("right", "prawo"),
    ("left", "lewo"),
    ("up", "góra"),
    ("down", "dół"),
    ("front", "przód"),
    ("back", "tył"),
    ("inside", "wewnątrz"),
    ("outside", "na zewnątrz"),
    ("fast", "szybki"),
    ("slow", "wolny"),
    ("strong", "silny"),
    ("weak", "słaby"),
    ("light", "lekki"),
    ("heavy", "ciężki"),
    ("young", "młody"),
    ("important", "ważny"),
    ("interesting", "interesujący"),
    ("different", "inny"),
    ("same", "ten sam"),
    ("full", "pełny"),
    ("empty", "pusty"),
    ("open", "otwarty"),
    ("closed", "zamknięty"),
    ("first", "pierwszy"),
    ("last", "ostatni"),
    ("mom", "mama")
]
